### ISSUE TITLE
How to deploy specific calico version on openshift 4.x

### ISSUE THREAD

**Issue by dbazhal** [tigera/operator#1045]
It would be cool to be able to deploy specific calico version or just update minor calico version

## Expected Behavior

I'd expect something like "put var here, i deploy calico of given version".

## Current Behavior

Nothing like that.

## Possible Solution

Add environment variable for that?

## Your Environment

Openshift 4.x

**Comment by caseydavenport** [comment]
@dbazhal the intended behavior is that each operator version corresponds to a particular Calico version. To update the Calico version, simply bump the version of the operator that you are running to one that installs the Calico version you want.

**Comment by caseydavenport** [comment]
This is intentional, since it guarantees that the config that is deployed matches and has been tested against the code it is deploying. If we allowed the operator to install arbitrary images, that would expose users to an opportunity to break their cluster by installing a version that isn't compatible with the way the operator config.

**Comment by g18yqu** [comment]
@caseydavenport ill look through the code and releases but are those calico tags easily retrievable? I'm trying to do air gapped deploys of calico operator and it'd be great if I had a straightforward to deploy what they are during staging.

**Comment by tmjd** [comment]
The notes with each release are expected to have the Calico version the release includes. So looking through the releases should give you that information.
