### ISSUE TITLE
windows node daemonset should have a priority class

### ISSUE THREAD

**Issue by lmm** [tigera/operator#1852]
## Expected Behavior

Critical component resources like the windows-upgrader daemonset should have a priority class.

## Current Behavior

The windows-upgrader daemonset does not have a priority class.

## Possible Solution

Add a priority class to the windows-upgrader daemonset template spec.

## Steps to Reproduce (for bugs)

1. Run an AKS cluster with calico (v3.21.4) policy enabled and windows nodes
2. Observe that the windows-upgrader daemonset doesn't have a priority class
3.
4.

## Context

This was raised by the AKS team. Not having a priority class means that the windows-upgrader pods can be preempted and disrupt the upgrade process.

## Your Environment

* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment]
@coutinhop WDYT if I rename this issue to be for the windows daemonset (`calico-node-windows`) because it has replaced the upgrader daemonset and it seems like the newer daemonset should have the Node Critical priority class? Is there any reason the calico-node-windows daemonset shouldn't have that priority class?

**Comment by coutinhop** [comment]
@tmjd agreed, the missing priority class was probably and oversight, will add
