### ISSUE TITLE
Migration to Tigera Operator does not perform due to all nodes with 'pre-operator' label

### ISSUE THREAD

**Issue by kifeo** [tigera/operator#1923]
I changed from the Calico manifest to operator via [https://projectcalico.docs.tigera.io/master/maintenance/operator-migration](https://projectcalico.docs.tigera.io/master/maintenance/operator-migration)

The deployment does not succeed as during the migration, it waits for linux nodes to be ready to deploy typha on.
However all my nodes are labeled with "projectcalico.org/operator-node-migration=pre-operator" and based on [https://github.com/tigera/operator/blob/7e92780ff8b376c9c0c17d911585d344ab06f9cb/pkg/controller/installation/typha_autoscaler.go#L237](https://github.com/tigera/operator/blob/7e92780ff8b376c9c0c17d911585d344ab06f9cb/pkg/controller/installation/typha_autoscaler.go#L237), this will not count the node as ready to deploy.

The error message is : 
{"level":"error","ts":1650617335.8234766,"logger":"typha_autoscaler","msg":"Failed to autoscale typha","error":"not enough linux nodes to schedule typha pods on, require 1 and have 0"}

## Expected Behavior

I would expect the operator to successfully deploy.

**Comment by tmjd** [comment]
I don't believe the log message you've provided is the cause for why the migration is not proceeding. I don't believe the operator will ever scale typha to zero. So even though you are seeing that message, there should still be a typha attempting to be deployed.
Is there a typha pod deployed in calico-system?
Do you see any logs from the operator with something like `waiting for typha to %d replicas, currently at %d`?

Could you share more of the logs from the operator?
It would also be helpful to share some general information about the cluster you're attempting to migrate. Like how big the cluster is, what cloud you're on if running in the cloud, what version of Calico you're trying to upgrade from, any info you think might be helpful.

> I would expect the operator to successfully deploy.

The operator has deployed, it is having trouble migrating, probably due to a pod not deploying or because of an issue with one of the currently running pods.

I would also suggest not using master for the best experience.

**Comment by kifeo** [comment]
Hi @tmjd ,

Thanks for the help on this one.

The is no pod in the calico-system namespace :
```
k get pod -n calico-system 
No resources found in calico-system namespace.
```

But there are the previous ones from the manifest :
```
k get pod -n kube-system
NAME                                      READY   STATUS    RESTARTS          AGE
calico-kube-controllers-7c845d499-rlhd8   1/1     Running   240 (6h37m ago)   9d
calico-node-b5s29                         1/1     Running   0                 9d
calico-node-d5hst                         1/1     Running   0                 9d
calico-node-js84z                         1/1     Running   0                 9d
calico-node-xtxvl                         1/1     Running   0                 9d
<snip>
```

and I have the operator in the tigera-operator namespace :
```
k get pod -n tigera-operator
NAME                               READY   STATUS    RESTARTS          AGE
tigera-operator-7d88459c9f-dtzbf   1/1     Running   349 (4h10m ago)   9d

```


Here are the logs from this operator 
`{"level":"info","ts":1650867716.590535,"logger":"status_manager.apiserver","msg":"Status manager is not ready to report component statuses."}
{"level":"info","ts":1650867721.586294,"logger":"status_manager.calico","msg":"Status manager is not ready to report component statuses."}
{"level":"info","ts":1650867721.5907133,"logger":"status_manager.apiserver","msg":"Status manager is not ready to report component statuses."}
{"level":"error","ts":1650867725.809479,"logger":"typha_autoscaler","msg":"Failed to autoscale typha","error":"not enough linux nodes to schedule typha pods on, require 1 and have 0"}
{"level":"info","ts":1650867726.5860388,"logger":"status_manager.calico","msg":"Status manager is not ready to report component statuses."}
{"level":"info","ts":1650867726.5902948,"logger":"status_manager.apiserver","msg":"Status manager is not ready to report component statuses."}
{"level":"info","ts":1650867731.5861654,"logger":"status_manager.calico","msg":"Status manager is not ready to report component statuses."}
{"level":"info","ts":1650867731.590486,"logger":"status_manager.apiserver","msg":"Status manager is not ready to report component statuses."}
{"level":"error","ts":1650867735.808899,"logger":"typha_autoscaler","msg":"Failed to autoscale typha","error":"not enough linux nodes to schedule typha pods on, require 1 and have 0"}
{"level":"info","ts":1650867736.5861042,"logger":"status_manager.calico","msg":"Status manager is not ready to report component statuses."}
{"level":"info","ts":1650867736.5904388,"logger":"status_manager.apiserver","msg":"Status manager is not ready to report component statuses."}
{"level":"error","ts":1650867737.8428767,"logger":"controller_installation","msg":"Failed to scale typha","Request.Namespace":"","Request.Name":"default","error":"not enough linux nodes to schedule typha pods on, require 1 and have 0","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214"}
{"level":"error","ts":1650867740.895501,"logger":"controller_installation","msg":"Failed to scale typha","Request.Namespace":"tigera-operator","Request.Name":"tigera-operator-token-b6bk6","error":"not enough linux nodes to schedule typha pods on, require 1 and have 0","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214"}
{"level":"info","ts":1650867741.5862803,"logger":"status_manager.calico","msg":"Status manager is not ready to report component statuses."}
{"level":"info","ts":1650867741.590456,"logger":"status_manager.apiserver","msg":"Status manager is not ready to report component statuses."}
{"level":"error","ts":1650867745.8666162,"logger":"controller_installation","msg":"Failed to scale typha","Request.Namespace":"tigera-operator","Request.Name":"default-token-b7vnw","error":"not enough linux nodes to schedule typha pods on, require 1 and have 0","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214"}
{"level":"info","ts":1650867746.58623,"logger":"status_manager.calico","msg":"Status manager is not ready to report component statuses."}
{"level":"info","ts":1650867746.590556,"logger":"status_manager.apiserver","msg":"Status manager is not ready to report component statuses."}
`

"I would also suggest not using master for the best experience." 
>>> I'm not sure to understand what you mean

**Comment by tmjd** [comment]
> "I would also suggest not using master for the best experience."

I meant you linked to https://projectcalico.docs.tigera.io/master/maintenance/operator-migration and you should instead use https://projectcalico.docs.tigera.io/maintenance/operator-migration so you are running the tagged, tested, and released code.

What do you see if you look at `kubectl describe -n calico-system deployment calico-typha`? 
That should show you the number of typha replicas that are desired (I'd expect 1 with what you've reported so far).
There might also be some useful information in the Events output of the describe. You might also need to describe the replicaset for calico-typha to find out why there are no pods being deployed.

Your output of pods in kube-system doesn't show any calico-typha pods, are there any in that namespace? I'm asking because if all the nodes have the "old" calico-typha there won't be room for the "new" calico-typha pods.

**Comment by kifeo** [comment]
I could not see anything after using the tagged code with the command provided.
However, I did edit a node and removed the tag "projectcalico.org/operator-node-migration=pre-operator" and then it could successfully deploy.

Thanks for the help @tmjd !

**Comment by tmjd** [comment]
Thanks for reporting back @kifeo
Is there any chance I could easily replicate your setup?
