### ISSUE TITLE
Guideline for migrate existing AWS Calico helm to tigera operator

### ISSUE THREAD

**Issue by nathanwang-comp** [tigera/operator#1948]
Please help provide a solution which can help use migrate existing AWS Calico helm to tigera operator. The solution should work for both new installation and existing AWS Calico installation.
I am doing auto update with terraform.

**Comment by tmjd** [comment]
Have you followed [this doc](https://projectcalico.docs.tigera.io/maintenance/operator-migration) which the [deprecation notice on aws-calico chart on amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-calico/README.md) point to?

If you do not think that is sufficient or it doesn't work I would suggest creating an Issue on [projectcalico/calico](https://github.com/projectcalico/calico) as that is the place where something like that would be documented.
You should also include what you have tried from the document (and any variations) and what went wrong.

Since it seems like this is already provided I'm going to close this issue. If you believe this issue needs to be opened back up please explain why and I can do so.
