### ISSUE TITLE
Add flag for optional deployment

### ISSUE THREAD

**Issue by dza89** [tigera/operator#1971]
## Expected Behavior

Deploy Tigera operator: 
Only deploy typha components or calico-node components when requested.

## Current Behavior

Typha and calico-node are both deployed. 

## Possible Solution

Add flag to the operator so it only deploys the components requested by deployer.

## Steps to Reproduce (for bugs)

n/a

## Context

We are using calico-node on EKS for network policies. Typha is not being used at all and counts as useless overhead.

**Comment by tmjd** [comment]
This is a duplicate of #1282.

>Typha is not being used at all and counts as useless overhead.

Typha is used in installations using the tigera operator, calico-node is always configured to connect to typha when using the operator.

Without a use case requiring typha to not be deployed, I don't think we will add functionality to disable the deployment of typha.
If you have a use case that requires not running typha please feel free to add a comment and I can re-open this issue.

**Comment by j-sepul** [comment]
I’d like to request a configuration option to explicitly disable Typha from the Calico operator configuration. Currently, Typha deployment is governed by the Installation custom resource, and there’s no direct Helm value or operator setting to avoid installing it by default.

From a security standpoint, having Typha running when it’s not required can introduce unnecessary exposure. Specifically, port 5473 (used by Typha) may present TLS vulnerabilities such as:

- SSL Medium Strength Cipher Suites (SWEET32)
- TLS 1.0 and 1.1 Protocol Usage

In some clusters (like small-scale k3s deployments), Typha isn’t needed. Allowing users to opt-out at the time of installation (via a Helm value or an operator setting) would improve security and reduce complexity. Implementing a direct and documented method to disable Typha out-of-the-box would be greatly appreciated.

**Comment by j-sepul** [comment]
I agree @tmjd , the Tigera Operator is presented as a particular deployment option for Calico. However, it is heavily recommended throughout various sections of the Calico documentation, suggesting it as the primary method for deployment. While this approach might suit specific scenarios, I believe the operator should provide more flexibility beyond an opinionated installation path. Ideally, it should allow for configuration of at least the most commonly used use cases.

One concern with the current approach is that it might inadvertently maintain vulnerabilities or limit the adaptability of the system to different deployment needs. Specifically, there should be a way to configure critical components like Typha directly via the operator's "installation configuration" or a similar mechanism. This would enhance usability and make the operator more applicable to diverse operational requirements.

By offering more configurable options within the operator, the deployment process would align better with varying use cases and environments, improving overall reliability and security.

Request:

- Consider making the Tigera Operator less opinionated by enabling more customization, particularly for widely used configurations.

- Provide a clear method to configure components like Typha during the installation phase through the operator's configuration.

**Comment by tmjd** [comment]
> However, it is heavily recommended throughout various sections of the Calico documentation, suggesting it as the primary method for deployment

Agreed, though it is also heavily recommended that typha be used so by that same argument we should not make Typha optional. The recommendation to use Typha is not stated widely because we have codified the recommendation in the operator by not making Typha optional. 

> Consider making the Tigera Operator less opinionated by enabling more customization, particularly for widely used configurations.

We have not seen evidence that configurations without Typha are widely used. If Typha-less configurations were widely used and were required, I would expect to see use cases explaining why Typha was not needed. This issue and the [one other github request to disable Typha](https://github.com/tigera/operator/issues/1282) have not included any use case for why Typha needs to be disabled.

> Provide a clear method to configure components like Typha during the installation phase through the operator's configuration.

There is configuration of Typha available through the [InstallationSpec](https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.InstallationSpec) with some typha deployment specific configuration available under the [typhaDeployment field](https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.TyphaDeployment).
