### ISSUE TITLE
how to add namespace selector

### ISSUE THREAD

**Issue by mo-saeed** [tigera/operator#2019]
in the old calico installation we used this helm chart https://github.com/aws/eks-charts/tree/master/stable/aws-calico and we were able to add nodeselector to spawn the nodes in specific nodes.

I have migrated my test cluster to tigera-operator and i had to remove the nodeselector from my existing deployments so tigera can migrate successfully 

is there a way to define nodeselector ?

## Expected Behavior

Able to define nodeselector so pods can run in specific nodes.

## Current Behavior

Not able to define nodeselector so pods can run in specific nodes.

## Steps to Reproduce (for bugs)

1- install calico with tigera-operator
2- use nodeselector key

## Your Environment

* Operating System and version: Linux ubuntu (kubernetes)
* latest operator version

**Comment by tmjd** [comment]
I believe this is available now by configuring the [calicoNodeDaemonSet](https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.CalicoNodeDaemonSet) field on the installation resource.

I'm closing this since I think this is addressed. Let me know if there is still an issue here and I can re-open. Also sorry that it took so long to get any kind of response on here.
