### ISSUE TITLE
User defined controlPlaneTolerations missing on calico-node pods

### ISSUE THREAD

**Issue by tlcowling** [tigera/operator#2020]
I've trying to use controlPlaneTolerations as defined in the reference [here](https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec) to control tolerations which get applied to the resources created by the operator.

## Expected Behavior

I expect when I set `controlPlaneTolerations` in the InstallationSpec, 
e.g.

```
spec:
  controlPlaneTolerations:
  - effect: NoExecute
     key: test
     operator: Equal
     value: value
```

to see this toleration appear on the calico-node pods in the same way it does for the Typha pods.  I'm presuming this is the expected behaviour because the description is

`ControlPlaneTolerations specify tolerations which are then globally applied to all resources created by the operator.`

## Current Behavior

After adding the `controlPlaneTolerations` in an `Installation`, the calico-node pods maintain the same broad existing default tolerations: 

```
  {
    "effect": "NoSchedule",
    "operator": "Exists"
  },
  {
    "effect": "NoExecute",
    "operator": "Exists"
  },
```

## Your Environment

EKS Node, Amazon Linux 2

**Comment by caseydavenport** [comment]
xref: https://github.com/projectcalico/calico/issues/6136

**Comment by tmjd** [comment]
I don't think [Calico #6136](https://github.com/projectcalico/calico/issues/6136) is applicable here. Because I think the request here is that `controlPlaneTolerations` should apply to calico-node. We don't consider calico-node to be part of the "control plane". So I think we could update the comment on `controlPlaneTolerations` to clarify that it does not apply to calico-node but we wouldn't make it apply to calico-node.

#1990 does apply though and I think would address being able to set configurations on the calico-node daemonset.

I am curious what your use case is for needing to be able to set tolerations on the calico-node daemonset. Would you please share your use case where you need to change the tolerations on calico-node? Thank you.

**Comment by tlcowling** [comment]
Hi @tmjd, thanks for the reply, yes you are right, the original issue was about the mechanism for adding custom tolerations to `calico-node`.   I misunderstood / accidentally ignored the intended meaning of "control plane" in `controlPlaneTolerations`  and focused on the description of the parameter in the docs as applying to all resources.   #1990 looks like what I am looking for
