### ISSUE TITLE
Installation CRD too long for kubectl apply

### ISSUE THREAD

**Issue by haslersn** [tigera/operator#2295]
The current Installation CRD is so long that it can no longer be updated with `kubectl apply` due to:

```
The CustomResourceDefinition "installations.operator.tigera.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

Tested with the tigera-operator manifest downloaded from: https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml

**Comment by lmm** [comment]
`kubectl replace` should get around this error.

**Comment by haslersn** [comment]
That's a workaround, but it's suboptimal when deploying the whole manifest at once, because then everything would get replaced instead of applied.

Furthermore, in declarative setups, the manifest might be part of a larger kustomize or Helm project. Also it's sometimes difficult to instruct CI pipelines or CD tools to use `kubectl replace` instead of `kubectl apply`.

**Comment by blegros-exte** [comment]
I agree that it is only a workaround. There's no issue displayed when upgrading the operator from Helm chart, hence no reason to think that something is wrong.
I dug a long time into Calico/Tigera operator project before finding that the Installation CRD was not updated.
The initial issue was coming from the operator that displayed logs about `csi-node-driver` daemonset that couldn't be updated because `kubeletVolumePluginPath` was not provided.

Turns out, Installation CRD was not up-to-date because Operator can't update it, nor kubectl apply can do it.

This is clearly misleading and the CRD installation/upgrade should work out of the box.

**Comment by tmjd** [comment]
Neither the helm chart nor the manifest being referred to in this issue come from this repo. If this is still an issue, an issue should be opened on https://github.com/projectcalico/calico as that is the source for the manifest and helm chart.
