### ISSUE TITLE
Blocking traffic to other service like to RDS, from LB in AWS

### ISSUE THREAD

**Issue by MuhammadNaeemAkhtar** [tigera/operator#2776]
## Expected Behavior

Need to deny traffic from all pods except form pod having label name=wso2

## Current Behavior

Once installed calico using helm in terraform 
```
resource "helm_release" "calico" {
  name       = "calico"
  repository = "https://docs.tigera.io/calico/charts"
  chart      = "tigera-operator"
  version    = "v3.25.1"
  namespace  = "tigera-operator"
  create_namespace = true

  set {
    name = "kubernetesProvider"
    value = "EKS"
  }
}
```

It starts blocking all the traffic and to resolve it I need to delete calico and refresh the node from Autoscaling group 

## Your Environment

* AWS EKS version 1.27
* VPC CNI version v1.13.3-eksbuild.1
* Operating System and version: Linux

**Comment by tmjd** [comment]
This sounds like you are having a network policy issue. I'd suggest you submit an issue to github.com/projectcalico/calico, issues on this repository should be focused on operator installation or update issues related to managing Calico components.
Also I'd suggest providing more information in your issue, like what network policies you've created. Because unless you've got a fundamental problem in your installation the default state is to not block any traffic.

**Comment by MuhammadNaeemAkhtar** [comment]
Hi @tmjd 
Thanks for your feedback. 
The strange is that I didn't yet created any network policy. As soon as I installed calico it blocks all the traffic.
