### ISSUE TITLE
With Tigera operator, applicative pod lost network after  windows nodes reboot

### ISSUE THREAD

**Issue by amapi** [tigera/operator#3193]
We have installed Calico with Tigera operator with WINDOWS nodes

* Operator version: 1.32.5
* Calico version: 3.27.2
* k8s: 1.27.6

Calico is running ok.

When we reboot a windows node. Calico pods start AFTER applicative pod.s 

Result: 

Applicative pods sandbox do not have any network. Pod loop in restart. Take care, POD loop in restart, but NOT the sandbox. So, until you delete the pod (and so, delete the sandbox), the pod is stuck in restart loop.

When we delete the pod (and the sandbox), as calico is already started this time, pod(and sandbox) si recreated with network this time.

We do not have this issue when calico was a windows service as calico service start before applicative pod.

Does someone have any idea.

Please: do not ask for usage of Readiness et Liveness Probes. We could not ask project hosted on the cluster to modify their deployment to add Readiness et Liveness Probes depending of calico node.

**Comment by tmjd** [comment]
@coutinhop could you take a look at this issue?

**Comment by coutinhop** [comment]
Just to close on this, I don't think there's much that can be done on the Calico (or Tigera operator) side, as this issue happens due to the way Windows handles the containers. There's no way to guarantee Calico pods start up before application pods, and if one does start up before Calico it won't have networking until it is restarted (after Calico is set up and running)...
