### ISSUE TITLE
tigera operator throws error every 5 minutes for ippool not created and managed by operator

### ISSUE THREAD

**Issue by scpham** [tigera/operator#3428]
We upgraded from tigera-operator-v3.27.0 to tigera-operator-v3.28.0 and its now throwing an error every 5 minutes with error message "Cannot update an IP pool not owned by the operator"

```
{"level":"error","ts":"2024-07-15T16:26:43Z","logger":"controller_ippool","msg":"Cannot update an IP pool not owned by the operator","Request.Namespace":"","Request.Name":"periodic-5m0s-reconcile-event","reason":"ResourceValidationError","stacktrace":"github.com/tigera/operator/pkg/controller/status.(*statusManager).SetDegraded\n\t/go/src/github.com/tigera/operator/pkg/controller/status/status.go:356\ngithub.com/tigera/operator/pkg/controller/ippool.(*Reconciler).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/ippool/pool_controller.go:291\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:226"}
```

## Expected Behavior

Not generate an error every 5 minutes if its not really an error. It appears calico is still operating fine.

## Current Behavior

Every 5 minutes it generates the error for an ippool that can't be managed

## Possible Solution

Give ability to tell the operator to manage it

## Steps to Reproduce (for bugs)

1. Manually create ippool default-ipv4-ippool
2. Install tigera-operator v3.28.0

## Context

Not clear on the actual impact, it appears calico is operating as expected but the error message is generated every 5 minutes.

## Your Environment

Large production AWS & Kubernetes 1.28 env.

**Comment by tmjd** [comment]
To start, there is no impact on operations.

@caseydavenport was there a reason we made this error instead of info?
I think we have a way to get this to stop (there might even be a couple). @caseydavenport do you remember what they might be?
I think one way was to ensure the IPPool in the Installation resource matches the IPPool resource and then add a label or annotation to the IPPool resource to make the operator think it owns the resource.
I'm not sure but there might have been another way by setting the IPPool section in the Installation resource to an empty list, like with `[]`, I think that is how we tell the operator that it shouldn't attempt to manage IPPools.
